### ISSUE TITLE
error messages when I run drive.sh

### ISSUE THREAD

**Issue by xuzhang5788** [simonfqy/PADME#15]
Running on dataset: tc_full_kinase
-------------------------------------
Traceback (most recent call last):
  File "driver.py", line 831, in <module>
    tf.compat.v1.app.run(main=run_analysis, argv=[sys.argv[0]] + unparsed)
  File "/home/pharma1/anaconda3/envs/DeepChem/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/pharma1/anaconda3/envs/DeepChem/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/pharma1/anaconda3/envs/DeepChem/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "driver.py", line 374, in run_analysis
    remove_val_set_entries=remove_val_set_entries)
TypeError: load_tc_full_kinases() got an unexpected keyword argument 'cold_drug_cluster'

When I run drivw2.sh, I got 

 import pandas.util.testing as tm
Traceback (most recent call last):
  File "driver.py", line 831, in <module>
    tf.compat.v1.app.run(main=run_analysis, argv=[sys.argv[0]] + unparsed)
  File "/home/pharma1/anaconda3/envs/DeepChem/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/pharma1/anaconda3/envs/DeepChem/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/pharma1/anaconda3/envs/DeepChem/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "driver.py", line 274, in run_analysis
    assert len(set(aggregate)) == len(aggregate)
TypeError: 'NoneType' object is not iterable

You listed many .sh files. Do they need to be run at the certain series? such as first run **.sh, then run ***.sh? It will be great to list the version of the libraries you used in your code. Many thanks for your great work.

**Comment by simonfqy** [comment]
I am very sorry that I did not get back to you earlier. Thank you for your kind words!
The `.sh` files are independent of each other, you don't need to run them according to any certain order.

As for the versions, I don't remember exactly, and I no longer have access to the GPU cluster I used for running this project. I was likely using TensorFlow 1.4, which was released in late 2017. The `DeepChem` version was likely the one available in Dec 2017 or Jan 2018, the exact version is 1.3.1, [this line](https://github.com/simonfqy/PADME/blob/e01c592cc06c4de04b3ed6db35da5af5ff7f863f/dcCustom/__init__.py#L8) shows the version number. 

Some code can be buggy, yes. If you still want to ask, please give me a bit more info, thanks~

If you have any more queries, please don't hesitate to ask me. I will try my best to assist you. Again, many apologies for not replying to you sooner.
